# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmodel',
            name='short_url',
            field=models.SlugField(max_length=10, unique=True, verbose_name='short url'),
        ),
    ]
